name: Development Workflow
on:
  push:
    branches:
      - '*'
jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Check code formatting
        run: yarn check-format

      - name: Run ESLint
        run: yarn lint
